language: r
cache: packages
latex: false
r_build_args: --no-build-vignettes
r_check_args: --as-cran --ignore-vignettes

r_packages:
  - covr

install:
  R -e 'install.packages(c("remotes","testthat"))'
  R -e 'remotes::install_deps(dependencies = c("Imports","LinkingTo"))'
  
env:
  global:
    - _R_CHECK_FORCE_SUGGESTS_: false
    - R_REMOTES_NO_ERRORS_FROM_WARNINGS: true

after_success:
  - Rscript -e 'covr::codecov()'

branches:
  only:
    - master
