language: r
cache: packages
latex: false
r_build_args: --no-build-vignettes
r_check_args: --as-cran --ignore-vignettes --no-tests --no-examples

r_packages:
  - covr
  
env:
  global:
    - _R_CHECK_FORCE_SUGGESTS_: false

after_success:
  - Rscript -e 'covr::codecov()'

branches:
  only:
    - master
